server:
  port: 8080

spring:
  ## 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tsa_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root


logging:
  config: classpath:logback/logback-dev.xml